default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  database: coop_list_test

production: &production
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

# Para Action Cable (WebSockets)
cable:
  <<: *production

# Para SolidQueue (fila de background jobs)
queue:
  <<: *production

# Para SolidCache (cache relacional do Rails 8)
cache:
  <<: *production
